before_install:
  - sudo mkdir -p /var/lib/update-notifier/package-data-downloads/partial/
  - sudo chown _apt /var/lib/update-notifier/package-data-downloads/partial/
  - sudo apt-get source linux-image-$(uname -r)

addons:
  apt:
    packages:
      manpages-dev
      manpages-posix-dev

language: cpp

script: ./count.sh

os:
  - linux
  - osx
